logging:
  level:
    org.springframework: warn
    org.flowable.engine.impl.persistence.entity.*: info
    org.flowable.task.service.impl.persistence.entity.*: info
    io.github.spafka.flowable.service.Graphs: trace
flowable:
  common:
    app:
      security:
        type: idm
      role-prefix:
      idm-admin:
        user: admin
        password: admin
  idm:
    ldap:
      enabled: false
    app:
      admin:
        user-id: admin
        password: admin
        first-name: wong
        last-name: hf
        email: spafka@163.com
  content:
    storage:
      root-folder: data/
      create-root: true
  process:
    definition-cache-limit: 512
    async:
      executor:
        default-async-job-acquire-wait-time-in-millis: 5000
        default-timer-job-acquire-wait-time-in-millis: 5000
  cmmn:
    async:
      executor:
        default-async-job-acquire-wait-time-in-millis: 5000
        default-timer-job-acquire-wait-time-in-millis: 5000
  rest:
    app:
      authentication-mode: verify-privilege
  task:
    app:
      rest-enabled: true
  admin:
    app:
      security:
        encryption:
          credentials-i-v-spec: j8kdO2hejA9lKmm6
          credentials-secret-spec: 9FGl73ngxcOoJvmL
  form-field-validation-enabled: false
  experimental:
    debugger:
      enabled: true
  database-schema-update: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: when_authorized
      roles: access-admin
  health:
    ldap:
      enabled: false

spring:
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  profiles:
    active: mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/flowabletest?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
      username: root
      password: root
      initialSize: 1
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      connectTimeout: 30000
      socketTimeout: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: druid
        login-password: druid
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true